absl-py==1.1.0
adjustText==0.7.3
affinegap==1.12
aiohttp @ file:///opt/concourse/worker/volumes/live/9e4bd7d9-f814-4862-5681-30883b9b8d6a/volume/aiohttp_1646806385231/work
aiosignal @ file:///tmp/build/80754af9/aiosignal_1637843061372/work
altair @ file:///home/conda/feedstock_root/build_artifacts/altair_1640799865332/work
altair-data-server==0.4.1
altair-saver==0.5.0
altair-viewer==0.4.0
appdirs==1.4.4
appnope @ file:///opt/concourse/worker/volumes/live/5f13e5b3-5355-4541-5fc3-f08850c73cf9/volume/appnope_1606859448618/work
argon2-cffi @ file:///opt/conda/conda-bld/argon2-cffi_1645000214183/work
argon2-cffi-bindings @ file:///opt/concourse/worker/volumes/live/0628405f-5e68-4591-7d86-fffe9a78a449/volume/argon2-cffi-bindings_1644569695448/work
arrow @ file:///opt/concourse/worker/volumes/live/ebed6601-38ad-467c-78a8-3d3663d44241/volume/arrow_1624645996932/work
astor==0.8.1
asttokens @ file:///opt/conda/conda-bld/asttokens_1646925590279/work
astunparse==1.6.3
async-timeout @ file:///tmp/build/80754af9/async-timeout_1637851218186/work
attrs @ file:///opt/conda/conda-bld/attrs_1642510447205/work
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
beautifulsoup4 @ file:///tmp/build/80754af9/beautifulsoup4_1631874778482/work
bibtexparser==1.1.0
bioinfokit @ file:///opt/conda/conda-bld/bioinfokit_1637461440147/work
bleach @ file:///opt/conda/conda-bld/bleach_1641577558959/work
blinker==1.4
blis==0.7.7
Bottleneck==1.3.2
branca==0.4.2
brotlipy==0.7.0
cachetools @ file:///tmp/build/80754af9/cachetools_1619597386817/work
cairocffi==1.3.0
CairoSVG==2.5.2
catalogue==2.0.7
certifi==2021.10.8
cffi @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/croot-2p6q7e2r/cffi_1642701115063/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
click @ file:///opt/concourse/worker/volumes/live/709f530a-8ffd-4e02-4f5f-9b3cfddd0e0b/volume/click_1646056616410/work
colorama @ file:///tmp/build/80754af9/colorama_1607707115595/work
ConfigArgParse==1.5.3
connection-pool==0.0.3
coverage @ file:///opt/concourse/worker/volumes/live/00956388-8f08-417e-60bd-ba8f2850c010/volume/coverage_1645539117474/work
crossrefapi==1.5.0
cryptography @ file:///opt/concourse/worker/volumes/live/0c46ebe2-a8f1-4d38-7a3c-36f6ad8d6408/volume/cryptography_1633520396142/work
cssselect2==0.5.0
cycler @ file:///tmp/build/80754af9/cycler_1637851556182/work
cymem==2.0.6
Cython @ file:///opt/concourse/worker/volumes/live/e35f601e-eb09-49c0-6fa6-ebbc312db11f/volume/cython_1639474582887/work
d6tcollect==1.0.6
d6tjoin @ git+https://github.com/d6t/d6tjoin.git@9618b129601aa0b4a9247d7001da8c2220d36d9c
d6tstack==0.2.0
datrie @ git+https://github.com/ashwinvis/datrie.git@8a7dc387a01af7ee0938c34edfd1fc497654ebbb
debugpy @ file:///opt/concourse/worker/volumes/live/e17abc9f-08a9-4dca-4e9b-e6d24bde47ce/volume/debugpy_1637091828617/work
decorator @ file:///opt/conda/conda-bld/decorator_1643638310831/work
defusedxml @ file:///tmp/build/80754af9/defusedxml_1615228127516/work
Deprecated @ file:///tmp/build/80754af9/deprecated_1615660604082/work
descartes==1.1.0
docutils==0.18.1
entrypoints==0.3
executing @ file:///opt/conda/conda-bld/executing_1646925071911/work
fake-useragent @ file:///home/conda/feedstock_root/build_artifacts/fake-useragent_1624623039956/work
filelock==3.4.2
flatbuffers==1.12
folium==0.12.1.post1
fonttools==4.25.0
free-proxy @ file:///home/conda/feedstock_root/build_artifacts/free-proxy_1641577289843/work
frozenlist @ file:///opt/concourse/worker/volumes/live/58e2cfac-148b-4139-5cce-70d9c831ec89/volume/frozenlist_1637767144664/work
future==0.18.2
gast==0.3.3
gender==0.0.30
Genderize==0.3.1
geographiclib==1.52
geopy==2.2.0
gitdb==4.0.9
GitPython==3.1.24
google-auth @ file:///opt/conda/conda-bld/google-auth_1646735974934/work
google-auth-oauthlib @ file:///tmp/build/80754af9/google-auth-oauthlib_1617120569401/work
google-pasta @ file:///Users/ktietz/demo/mc3/conda-bld/google-pasta_1630577991354/work
google-search-results==2.4.1
greenlet==1.1.2
grpcio @ file:///opt/concourse/worker/volumes/live/b549791f-b47d-49ca-7293-5d53b55def5a/volume/grpcio_1614884176451/work
h5py @ file:///opt/concourse/worker/volumes/live/ca975206-a8f5-4947-64c0-5af2e33e601d/volume/h5py_1593454180658/work
habanero==1.0.0
html5lib==1.1
huggingface-hub==0.4.0
idna @ file:///tmp/build/80754af9/idna_1637925883363/work
importlib-metadata @ file:///opt/concourse/worker/volumes/live/68796648-0236-4a85-4beb-f1ddd08dccd5/volume/importlib-metadata_1638542894284/work
iniconfig==1.1.1
install==1.3.5
ipykernel @ file:///opt/concourse/worker/volumes/live/675cc243-e35d-4e85-47e2-838adcdd7698/volume/ipykernel_1647000791373/work/dist/ipykernel-6.9.1-py3-none-any.whl
ipython @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_croot-uzw2qxt6/ipython_1646949517112/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipywidgets @ file:///tmp/build/80754af9/ipywidgets_1634143127070/work
jedi @ file:///opt/concourse/worker/volumes/live/fb2e45f1-1dff-42fa-6cab-bd094a4c4372/volume/jedi_1644315264796/work
jellyfish==0.9.0
Jinja2 @ file:///opt/conda/conda-bld/jinja2_1647436528585/work
joblib @ file:///tmp/build/80754af9/joblib_1635411271373/work
jsonschema @ file:///Users/ktietz/demo/mc3/conda-bld/jsonschema_1630511932244/work
jupyter==1.0.0
jupyter-client @ file:///opt/conda/conda-bld/jupyter_client_1643638337975/work
jupyter-console @ file:///opt/conda/conda-bld/jupyter_console_1647002188872/work
jupyter-core @ file:///opt/concourse/worker/volumes/live/d74cfa15-eb85-4119-7aea-67f807ff4440/volume/jupyter_core_1646994469397/work
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab-widgets @ file:///tmp/build/80754af9/jupyterlab_widgets_1609884341231/work
keras==2.9.0
Keras-Preprocessing @ file:///tmp/build/80754af9/keras-preprocessing_1612283640596/work
kiwisolver @ file:///Users/builder/miniconda3/envs/prefect/conda-bld/kiwisolver_1638569885739/work
langcodes==3.3.0
libclang==14.0.1
lxml @ file:///opt/concourse/worker/volumes/live/438351ba-3a65-48bb-7bf6-ad8311407699/volume/lxml_1646642665142/work
Markdown @ file:///opt/concourse/worker/volumes/live/3da0a8d0-509b-4685-6a53-c40b324889d7/volume/markdown_1614363821960/work
MarkupSafe @ file:///opt/concourse/worker/volumes/live/c9141381-1dba-485b-7c96-99007bf7bcfd/volume/markupsafe_1621528150226/work
matplotlib @ file:///opt/concourse/worker/volumes/live/4863dc73-443d-42f7-68bf-489aaa0e23a1/volume/matplotlib-suite_1638289695940/work
matplotlib-inline @ file:///tmp/build/80754af9/matplotlib-inline_1628242447089/work
matplotlib-venn @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-venn_1603640976466/work
mistune @ file:///opt/concourse/worker/volumes/live/95802d64-d39c-491b-74ce-b9326880ca54/volume/mistune_1594373201816/work
mizani==0.7.3
mkl-fft==1.3.1
mkl-random @ file:///opt/concourse/worker/volumes/live/f196a661-8e33-4aac-63bc-efb2ff50e035/volume/mkl_random_1626186080069/work
mkl-service==2.4.0
mpmath==1.2.1
multidict @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/croot-af6k74k7/multidict_1640703861097/work
munkres==1.1.4
murmurhash==1.0.6
nbclient @ file:///tmp/build/80754af9/nbclient_1645431659072/work
nbconvert @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/croot-r4wh23j5/nbconvert_1641309205559/work
nbformat @ file:///tmp/build/80754af9/nbformat_1617383369282/work
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1613680548246/work
networkx==2.7.1
nltk @ file:///tmp/build/80754af9/nltk_1592496090529/work
notebook @ file:///opt/concourse/worker/volumes/live/04354d80-9f15-4db9-4bcd-195dc104f1c6/volume/notebook_1645002579570/work
numexpr @ file:///opt/concourse/worker/volumes/live/52f18ae0-3912-48f4-7832-7d22abf43616/volume/numexpr_1640704220628/work
numpy @ file:///opt/concourse/worker/volumes/live/ceac9fd4-1ae1-48f8-612a-0c99bf783d0e/volume/numpy_and_numpy_base_1634106709647/work
oauthlib @ file:///opt/conda/conda-bld/oauthlib_1644332107998/work
opt-einsum @ file:///tmp/build/80754af9/opt_einsum_1621500238896/work
packaging @ file:///tmp/build/80754af9/packaging_1637314298585/work
palettable==3.3.0
pandas==1.3.4
pandocfilters @ file:///opt/conda/conda-bld/pandocfilters_1643405455980/work
parso @ file:///opt/conda/conda-bld/parso_1641458642106/work
pathy==0.6.1
patsy==0.5.2
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow==9.0.1
plotnine==0.6.0
pluggy==1.0.0
portpicker==1.5.0
powerlaw @ file:///home/conda/feedstock_root/build_artifacts/powerlaw_1589637974211/work
pprintpp==0.4.0
preshed==3.0.6
prometheus-client @ file:///opt/conda/conda-bld/prometheus_client_1643788673601/work
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1633440160888/work
protobuf==3.15.8
psutil==5.9.0
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
PuLP==2.6.0
pure-eval @ file:///opt/conda/conda-bld/pure_eval_1646925070566/work
py==1.11.0
pyasn1 @ file:///Users/ktietz/demo/mc3/conda-bld/pyasn1_1629708007385/work
pyasn1-modules==0.2.8
pycountry==22.3.5
pycountry-convert==0.7.2
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pydantic==1.8.2
Pygments @ file:///opt/conda/conda-bld/pygments_1644249106324/work
PyJWT @ file:///opt/concourse/worker/volumes/live/4b23e6f5-19fd-4072-46f2-afa3ad67289b/volume/pyjwt_1619651619662/work
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1635333100036/work
pyparsing @ file:///tmp/build/80754af9/pyparsing_1635766073266/work
pyrsistent @ file:///opt/concourse/worker/volumes/live/ac52847c-5646-4583-7286-af47061006cb/volume/pyrsistent_1636111017177/work
PySocks @ file:///opt/concourse/worker/volumes/live/85a5b906-0e08-41d9-6f59-084cee4e9492/volume/pysocks_1594394636991/work
pytest==7.1.1
pytest-cov==3.0.0
pytest-mock==3.7.0
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
python-dotenv @ file:///home/conda/feedstock_root/build_artifacts/python-dotenv_1636649191224/work
pytz==2021.3
PyYAML==6.0
pyzmq @ file:///opt/concourse/worker/volumes/live/12b008ff-2acb-4e15-682d-fce50395a9d4/volume/pyzmq_1638434992289/work
qtconsole @ file:///opt/conda/conda-bld/qtconsole_1643819126524/work
QtPy @ file:///opt/conda/conda-bld/qtpy_1643087291789/work
ratelimiter==1.2.0.post0
regex @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/croot-325xby49/regex_1642021452041/work
reportlab==3.6.9
repoze.lru==0.7
requests @ file:///opt/conda/conda-bld/requests_1641824580448/work
requests-oauthlib==1.3.0
rsa @ file:///tmp/build/80754af9/rsa_1614366226499/work
sacremoses==0.0.49
scholarly @ file:///home/conda/feedstock_root/build_artifacts/scholarly_1639880499649/work
scikit-learn @ file:///opt/concourse/worker/volumes/live/09b793c0-41c8-469b-7e31-b4a39bc68d95/volume/scikit-learn_1642617120730/work
scipy==1.8.0
seaborn @ file:///tmp/build/80754af9/seaborn_1629307859561/work
selenium @ file:///Users/runner/miniforge3/conda-bld/selenium_1636728070353/work
Send2Trash @ file:///tmp/build/80754af9/send2trash_1632406701022/work
six @ file:///tmp/build/80754af9/six_1644875935023/work
skorch==0.11.0
smart-open==5.2.1
smmap==5.0.0
snakemake==6.12.3
soupsieve @ file:///tmp/build/80754af9/soupsieve_1636706018808/work
spacy==3.2.4
spacy-legacy==3.0.9
spacy-loggers==1.0.1
sphinx-rtd-theme @ file:///Users/ktietz/demo/mc3/conda-bld/sphinx_rtd_theme_1629455006846/work
SQLAlchemy==1.4.31
srsly==2.4.2
stack-data @ file:///opt/conda/conda-bld/stack_data_1646927590127/work
statsmodels==0.13.2
stopit==1.1.2
svglib==1.2.1
tabulate==0.8.9
tensorboard==2.9.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.6.0
tensorflow==2.9.1
tensorflow-estimator==2.9.0
tensorflow-io-gcs-filesystem==0.26.0
termcolor==1.1.0
terminado @ file:///opt/concourse/worker/volumes/live/77a7a2fc-5569-4ff8-4f8c-22be111c7b5e/volume/terminado_1644322600385/work
testpath @ file:///tmp/build/80754af9/testpath_1624638946665/work
textwrap3==0.9.2
thinc==8.0.15
threadpoolctl @ file:///Users/ktietz/demo/mc3/conda-bld/threadpoolctl_1629802263681/work
tinycss2==1.1.1
tokenizers==0.11.6
tomli==2.0.1
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1636177962100/work
toposort==1.7
torch==1.11.0
torchtext==0.12.0
torchvision==0.12.0
tornado @ file:///opt/concourse/worker/volumes/live/05341796-4198-4ded-4a9a-332fde3cdfd1/volume/tornado_1606942323372/work
tqdm @ file:///opt/conda/conda-bld/tqdm_1647339053476/work
traitlets @ file:///tmp/build/80754af9/traitlets_1636710298902/work
transformers==4.17.0
typer==0.4.0
typing-extensions @ file:///tmp/build/80754af9/typing_extensions_1631814937681/work
Unidecode @ file:///home/conda/feedstock_root/build_artifacts/unidecode_1645371071762/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1641584929973/work
vega-datasets==0.9.0
wasabi==0.9.0
wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work
webencodings==0.5.1
Werkzeug @ file:///opt/conda/conda-bld/werkzeug_1645628268370/work
widgetsnbextension @ file:///opt/concourse/worker/volumes/live/b79a6318-0a66-44c8-744e-87eba0d202e8/volume/widgetsnbextension_1645009378090/work
wrapt @ file:///opt/concourse/worker/volumes/live/44cb0d08-9295-4ea1-6561-bec2dc079522/volume/wrapt_1638433869252/work
yarl @ file:///opt/concourse/worker/volumes/live/fd1429a0-40c2-4b4b-63f5-1e3d849157dd/volume/yarl_1606940018548/work
zipp @ file:///opt/conda/conda-bld/zipp_1641824620731/work
